## **Basics of PyTorch**
PyTorch is an open-source machine learning library widely used for applications such as computer vision, natural language processing, and more. It is favored by researchers and practitioners due to its dynamic computation graph, which allows for more flexibility and easier debugging.
At the core of PyTorch are tensors.

In this notebook, we will cover the basics of PyTorch and tensors, including:

1. Installation: How to install PyTorch on your machine.

2. Creating Tensors: Various ways to create tensors in PyTorch.

3. Tensor Operations: Basic operations that can be performed on tensors.

By the end of this notebook, you should have a solid understanding of how to use PyTorch and tensors for basic machine learning tasks. Let's get started!



#### **Prerequisites**
1. Make sure Python version is `3.8` or greater.

2. It is recommended, but not required, that your system has an NVIDIA GPU in order to harness
the full power of PyTorch’s CUDA support. To use CUDA follow Nvidia's Installation Guide for Windows and Linux.

 **All tasks performed today can be done using CPU alone. PyTorch defaults to storing tensors on cpu.**


#### **Installation**
To get started with PyTorch, you need to have it installed on your system.

1. **Windows**
- To install without CUDA
`pip3 install torch torchvision torchaudio`

- To install with CUDA
`pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121`

2. **Mac**
- CUDA is not available on MacOS, therefore default package is installed
`pip3 install torch torchvision torchaudio`

3. **Linux**
- To install without CUDA
`pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu`

- To install with CUDA
`pip3 install torch torchvision torchaudio`


For further details, you can also use the [PyTorch start locally guide](https://pytorch.org/get-started/locally/) on PyTorch's website.

### **Tensors**

At the core of PyTorch are `tensors`. Tensors are multi-dimensional arrays that are similar to NumPy arrays but with additional capabilities for GPU acceleration. Understanding tensors is fundamental to using PyTorch effectively, as they are the primary data structure used for storing and manipulating data in deep learning models.

In [1]:
import torch

Tensor Creation


In [2]:
#Directly from data
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [3]:
# From Numpy array
import numpy as np
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


In [4]:
# From other tensors
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")
x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.3481, 0.0339],
        [0.9771, 0.4807]]) 



In [5]:
# Populating tensors with random/constant values

shape = (2, 3,) # tuple of tensor dimensions
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
torch.manual_seed(1789)
rand_tensor = torch.rand(shape)
empty_tensor = torch.empty(shape) # memory is allocated, tensor populated with garbage- values
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")
print(f"Empty Tensor: \n {empty_tensor}")


Random Tensor: 
 tensor([[0.9631, 0.4014, 0.7564],
        [0.5782, 0.5438, 0.1929]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
Empty Tensor: 
 tensor([[5.3107e-13, 0.0000e+00, 5.1809e+22],
        [4.5574e-41, 1.4013e-45, 0.0000e+00]])


Using `seed` allows you to reproduce same random tensors across runs. When you set a seed for a random number generator, you initialize it to a specific value, which makes sure that the sequence of random numbers generated is the same every time you run your code. This is especially useful in research settings - where you’ll want some assurance of the reproducibility of your results.

#### **Tensor Attributes**
Tensor attributes describe their shape, datatype, and the device on which they are stored.


1. **Shape** - The extent of each dimension of a tensor
   

In [6]:
x = torch.empty(2, 2, 3)
print(x.shape,"\n")
print(x)


torch.Size([2, 2, 3]) 

tensor([[[4.7079e-12, 0.0000e+00, 4.7180e-12],
         [0.0000e+00, 5.4382e-01, 1.9294e-01]],

        [[0.0000e+00, 0.0000e+00, 1.4013e-45],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])


2. **Datatype** - An object that represents the data type of a `torch.Tensor`. PyTorch has twelve different data types. They offer various precision and range options fo numerical operations in PyTorch

In [7]:
a = torch.ones((2, 3), dtype=torch.int16)
print(a.dtype)
a = torch.ones((2, 3), dtype=torch.float64)
print(a.dtype)
a = torch.ones((2, 3), dtype=torch.int8)
print(a.dtype)
a = torch.ones((2, 3), dtype=torch.int32)
print(a.dtype)
a = torch.ones((2, 3), dtype=torch.int64)
print(a.dtype)
a = torch.ones((2, 3), dtype=torch.bool)
print(a.dtype)


torch.int16
torch.float64
torch.int8
torch.int32
torch.int64
torch.bool


3. **Device** - Object representing the device on which a `torch.Tensor` is or will be allocated.

In [8]:
# Create a tensor
tensor = torch.rand(3, 2)
print(f"Device tensor is initially stored on: {tensor.device}")



Device tensor is initially stored on: cpu


### Operations on Tensors

PyTorch defines over 100 tensor operations, including arithmetic, linear algebra, matrix manipulation (transposing, indexing, slicing), sampling, and more.

**Note :**
Each of these operations can be run on the GPU (at typically higher speeds than on a CPU). By default, tensors are created on the CPU. We need to explicitly move tensors to the GPU using .to method (after checking for GPU availability).


In [9]:
# Check if GPU is available and move tensor to GPU if it is
if torch.cuda.is_available():
    tensor = tensor.to("cuda")
    print(f"Device tensor is now stored on: {tensor.device}")
else:
    print("CUDA is not available. Tensor remains on CPU.")

CUDA is not available. Tensor remains on CPU.


**Numpy-like Indexing and Slicing**

In [10]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}","\n")
print(f"First column: {tensor[:, 0]}","\n")
print(f"Last column: {tensor[:, -1]}","\n")
tensor[:,1] = 0 # set all elements in second column to 0
print(tensor)


First row: tensor([1., 1., 1., 1.]) 

First column: tensor([1., 1., 1., 1.]) 

Last column: tensor([1., 1., 1., 1.]) 

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**Arithmetic operations**

In [11]:
ones = torch.zeros(2, 2) + 1 # adding 1 to a tensor of zeros
twos = torch.ones(2, 2) * 2 # multiplying a tensor of ones by 2
threes = (torch.ones(2, 2) * 7 - 1) / 2 # chaining operations
fours = twos ** 2 # squaring a tensor
sqrt2s = twos ** 0.5 # square root of a tensor

print(ones,"\n")
print(twos,"\n")
print(threes,"\n")
print(fours,"\n")
print(sqrt2s,"\n")





tensor([[1., 1.],
        [1., 1.]]) 

tensor([[2., 2.],
        [2., 2.]]) 

tensor([[3., 3.],
        [3., 3.]]) 

tensor([[4., 4.],
        [4., 4.]]) 

tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]]) 



 **Similar operations can be performed between two tensors:**

In [12]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]]) # element-wise exponentiation
print(powers2,"\n")
fives = ones + fours # element-wise addition
print(fives,"\n")
dozens = threes * fours # element-wise multiplication
print(dozens,"\n")

tensor([[ 2.,  4.],
        [ 8., 16.]]) 

tensor([[5., 5.],
        [5., 5.]]) 

tensor([[12., 12.],
        [12., 12.]]) 



**Note :** Please make sure to check the shapes of the tensors before performing these operations, otherwise they'll result in errors.

**Tensor Broadcasting**

The exception to the same-shapes rule is tensor broadcasting. Broadcasting is a feature in PyTorch (and other numerical libraries like NumPy) that allows operations between tensors of different shapes. It automatically adjusts the shapes of tensors to make their dimensions compatible for element-wise operations.

In [13]:
rand = torch.rand(2, 4) # random tensor
doubled = rand * (torch.ones(1, 4) * 2) # broadcasting
print(rand)
print(doubled)


tensor([[0.2569, 0.8153, 0.3774, 0.6209],
        [0.8973, 0.6783, 0.8594, 0.6721]])
tensor([[0.5138, 1.6306, 0.7549, 1.2419],
        [1.7946, 1.3567, 1.7187, 1.3442]])


In the above example , the 1x4 tensor is multiplied by both rows of the 2x4 tensor.

The rules for broadcasting are:
1. Each tensor must have at least one dimension - no empty tensors.
2. Comparing the dimension sizes of the two tensors, _going from last to first:

    - Each dimension must be equal, or
    - One of the dimensions must be of size 1, or
    - The dimension does not exist in one of the tensors.

Tensors of identical shape, of course, are trivially “broadcastable”.

Here are some examples of situations that honor the above rules and allow broadcasting:



In [14]:
a = torch.ones(4, 3, 2)
b = a * torch.rand(3, 2)
print(b, "\n") # 3rd & 2nd dims identical to a, dim 1 absent
c = a * torch.rand(4, 1, 2)
print(c, "\n") # 3rd dim = 1, 2nd dim identical to a
d = a * torch.rand(1, 3, 2)
print(d, "\n") # 3rd dim identical to a, 2nd dim = 1


tensor([[[0.4544, 0.6353],
         [0.5914, 0.9689],
         [0.5715, 0.7136]],

        [[0.4544, 0.6353],
         [0.5914, 0.9689],
         [0.5715, 0.7136]],

        [[0.4544, 0.6353],
         [0.5914, 0.9689],
         [0.5715, 0.7136]],

        [[0.4544, 0.6353],
         [0.5914, 0.9689],
         [0.5715, 0.7136]]]) 

tensor([[[0.4606, 0.7056],
         [0.4606, 0.7056],
         [0.4606, 0.7056]],

        [[0.5921, 0.0557],
         [0.5921, 0.0557],
         [0.5921, 0.0557]],

        [[0.3866, 0.2989],
         [0.3866, 0.2989],
         [0.3866, 0.2989]],

        [[0.8993, 0.2320],
         [0.8993, 0.2320],
         [0.8993, 0.2320]]]) 

tensor([[[0.2450, 0.1956],
         [0.8150, 0.1024],
         [0.2813, 0.7884]],

        [[0.2450, 0.1956],
         [0.8150, 0.1024],
         [0.2813, 0.7884]],

        [[0.2450, 0.1956],
         [0.8150, 0.1024],
         [0.2813, 0.7884]],

        [[0.2450, 0.1956],
         [0.8150, 0.1024],
         [0.2813, 0.7884]]]) 

##### **Common Functions**

**Mathematical Functions**

In [15]:
import math

a = torch.rand(2, 4) * 2 - 1 # random tensor in range [-1, 1]
print(torch.abs(a),"\n") #absolute value
print(torch.ceil(a),"\n") #ceiling
print(torch.floor(a),"\n") #floor
print(torch.clamp(a, -0.5, 0.5)) #clamping: values < -0.5 set to -0.5, values > 0.5 set to 0.5


tensor([[0.8933, 0.1511, 0.7021, 0.4549],
        [0.2857, 0.2995, 0.6397, 0.6817]]) 

tensor([[-0., -0., -0., -0.],
        [1., -0., 1., -0.]]) 

tensor([[-1., -1., -1., -1.],
        [ 0., -1.,  0., -1.]]) 

tensor([[-0.5000, -0.1511, -0.5000, -0.4549],
        [ 0.2857, -0.2995,  0.5000, -0.5000]])


**Trigonometric Functions and Their Inverses**

In [16]:
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4]) # angles in radians
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\nSine and arcsine:')
print(angles,"\n")
print(sines,"\n")
print(inverses,"\n")



Sine and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562]) 

tensor([0.0000, 0.7071, 1.0000, 0.7071]) 

tensor([0.0000, 0.7854, 1.5708, 0.7854]) 



**Bitwise Operations**

In [17]:
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))


tensor([3, 2, 1])


**Comparisons**

In [18]:
print('\nBroadcasted, element-wise equality comparison:')
d = torch.tensor([[1., 2.], [3., 4.]])
print(d,"\n")
e = torch.ones(1, 2)  # many comparison ops support broadcasting!
print(e,"\n")
print(torch.eq(d, e))  # returns a tensor of type bool



Broadcasted, element-wise equality comparison:
tensor([[1., 2.],
        [3., 4.]]) 

tensor([[1., 1.]]) 

tensor([[ True, False],
        [False, False]])


**Reductions**

In [19]:
d = torch.tensor([[1., 2.], [3., 4.]])
print(torch.max(d))
print(torch.max(d).item())
print(torch.mean(d))
print(torch.std(d))
print(torch.prod(d))
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2])))  # filter unique elements


tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])


**Vector and Linear Algebra Operations**



In [20]:
v1 = torch.tensor([1., 0., 0.])  # x unit vector
v2 = torch.tensor([0., 1., 0.])  # y unit vector

print(torch.cross(v1, v2),"\n")  # returns cross product of vectors v1 and v2

m1 = torch.rand(2, 2)  # random matrix
m2 = torch.tensor([[3., 0.], [0., 3.]])  # three times identity matrix
print(m1,"\n")
m3 = torch.matmul(m1, m2)  # same as m3 = m1@m2
print(m3,"\n")
print(torch.svd(m3),"\n")  # singular value decomposition


tensor([0., 0., 1.]) 

tensor([[0.0902, 0.7986],
        [0.4120, 0.8499]]) 

tensor([[0.2705, 2.3959],
        [1.2360, 2.5498]]) 

torch.return_types.svd(
U=tensor([[-0.6444, -0.7647],
        [-0.7647,  0.6444]]),
S=tensor([3.6687, 0.6192]),
V=tensor([[-0.3051,  0.9523],
        [-0.9523, -0.3051]])) 



/tmp/ipykernel_1369/3018723044.py:4: UserWarning: Using torch.cross without specifying the dim arg is deprecated.
Please either pass the dim explicitly or simply use torch.linalg.cross.
The default value of dim will change to agree with that of linalg.cross in a future release. (Triggered internally at /pytorch/aten/src/ATen/native/Cross.cpp:63.)
  print(torch.cross(v1, v2),"\n")  # returns cross product of vectors v1 and v2


#### **Altering Tensors in Place**

Most binary operations on tensors will return a third, new tensor.When we say `c = a * b`
(where a and b are tensors), the new tensor c will occupy a region of memory distinct from the
other tensors.

There are times, though, that you may wish to alter a tensor in place. For this, most of the math
functions have a version with an appended underscore `( _ )` that will alter a tensor in place.

In [21]:
a = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('a:')
print(a)
print(torch.sin(a))  # this operation creates a new tensor in memory
print(a)  # a has not changed

b = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('\nb:')
print(b)
print(torch.sin_(b))  # note the underscore
print(b)  # b has changed


a:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 2.3562])

b:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7071, 1.0000, 0.7071])


**For Arithmetic Operations:**

In [22]:
a = torch.ones(2, 2)
b = torch.rand(2, 2)
print('Before:')
print(a)
print(b)
print('\nAfter adding:')
print(a.add_(b))
print(a)
print(b)
print('\nAfter multiplying')
print(b.mul_(b))
print(b)


Before:
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.5300, 0.3159],
        [0.7081, 0.1727]])

After adding:
tensor([[1.5300, 1.3159],
        [1.7081, 1.1727]])
tensor([[1.5300, 1.3159],
        [1.7081, 1.1727]])
tensor([[0.5300, 0.3159],
        [0.7081, 0.1727]])

After multiplying
tensor([[0.2809, 0.0998],
        [0.5014, 0.0298]])
tensor([[0.2809, 0.0998],
        [0.5014, 0.0298]])


Using the `out` Argument for In-Place Computations:

There is another option for placing the result of a computation in an existing, allocated tensor. Many of the methods and functions we’ve seen so far - including creation methods! - have an `out` argument that lets you specify a tensor to receive the output. If the out tensor is the correct shape and `dtype` , this can happen without a new memory allocation:




In [23]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.zeros(2, 2)
old_id = id(c)
print(c,"\n")
d = torch.matmul(a, b, out=c)
print(c,"\n") # contents of c have changed

assert c is d # test c & d are same object, not just containing equal values # make sure that our new c is the same object as the old one
assert id(c) == old_id

torch.rand(2, 2, out=c) # works for creation too!
print(c,"\n") # c has changed again

assert id(c) == old_id # still the same object!






tensor([[0., 0.],
        [0., 0.]]) 

tensor([[0.4621, 0.5195],
        [0.1035, 0.1086]]) 

tensor([[0.7443, 0.7234],
        [0.7417, 0.6321]]) 



#### **Manipulating Tensor Shape**


In [24]:
a = torch.tensor([1, 2, 3, 4])
a_reshaped = torch.reshape(a, (2, 2))
print(a_reshaped,"\n")

b = torch.rand(56, 56)  # Consider 56x56 image
c = b.unsqueeze(0)  # unsqueeze(i) adds dimension of length 1 at index i
print(c,"\n")  # c is now a batch of 1 image of shape 56x56

d = torch.rand(1, 20)
print(d.shape,"\n")
e = d.squeeze(0)  # squeeze(i) removes a dimension if shape[i] is 1
print(e.shape,"\n")

x, y, z = torch.rand(2, 3), torch.rand(2, 3), torch.rand(2, 3)
cat_tensor = torch.cat((x, y, z), dim=0)  # concatenates tensors along rows
print(cat_tensor)


tensor([[1, 2],
        [3, 4]]) 

tensor([[[0.2893, 0.1629, 0.1285,  ..., 0.2148, 0.4567, 0.4887],
         [0.4287, 0.6620, 0.0410,  ..., 0.0035, 0.2118, 0.5679],
         [0.5858, 0.9733, 0.3692,  ..., 0.6938, 0.0219, 0.6840],
         ...,
         [0.7916, 0.7293, 0.6940,  ..., 0.1591, 0.5954, 0.1723],
         [0.3036, 0.3075, 0.0482,  ..., 0.1157, 0.1832, 0.4325],
         [0.0244, 0.9426, 0.9898,  ..., 0.9208, 0.1439, 0.2637]]]) 

torch.Size([1, 20]) 

torch.Size([20]) 

tensor([[0.2854, 0.0043, 0.2710],
        [0.6577, 0.9595, 0.6804],
        [0.7525, 0.3462, 0.6816],
        [0.7475, 0.8048, 0.6805],
        [0.6754, 0.7080, 0.1422],
        [0.7200, 0.5164, 0.3350]])


**Note:** The way to understand the “axis” or "dim" of a torch function is that it collapses the specified axis.

**Copying Tensors**

Assigning a tensor to a variable makes the variable a ***label*** of the tensor, and does not ***copy*** it.

For example:

In [25]:
a = torch.ones(2, 2)
b=a
a[0][1] = 561 # we change a...
print(b) # ...and b is also altered


tensor([[  1., 561.],
        [  1.,   1.]])


But what if you want a separate copy of the data to work on? The `clone()` method is there for you:

In [26]:
a = torch.ones(2, 2)
b = a.clone()

assert b is not a # different objects in memory...
print(torch.eq(a,b)) # ...but still with the same contents!
a[0][1] = 561 # a changes...
print(b)   # ...but b is still all ones






tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])


#### **Moving to GPU**

First, check whether a GPU is available:



In [27]:
if torch.cuda.is_available():
    print('We have a GPU!')
else:
    try:
        device = torch.device("mps")
        print("MPS available!")
    except:
        print('Sorry, CPU only.')


MPS available!


You can move your tensor to the GPU using the `.to()` method:

In [28]:
my_device = torch.device('cpu')

if torch.cuda.is_available():
    my_device = torch.device('cuda')
else:
    try:
        # Attempt to set device to mps
        temp_device = torch.device("mps")
        # Test if a simple operation works on MPS to catch NotImplementedError early
        _ = torch.rand(1, 1, device=temp_device)
        my_device = temp_device
    except NotImplementedError:
        print("MPS backend encountered a NotImplementedError, falling back to CPU.")
        my_device = torch.device('cpu')
    except Exception as e:
        print(f"An unexpected error occurred while checking MPS: {e}, falling back to CPU.")
        my_device = torch.device('cpu')

x = torch.rand(2, 2, device=my_device)
print(f"Tensor created on device: {my_device}")
print(x)

MPS backend encountered a NotImplementedError, falling back to CPU.
Tensor created on device: cpu
tensor([[0.1107, 0.1027],
        [0.5759, 0.5720]])


If you have an existing tensor living on one device, you can move it to another with the `to()` method.

In [29]:
y = torch.rand(2, 2)
y = y.to(my_device)


### **Numpy Bridge**

If you have existing ML or scientific code with data stored in NumPy `ndarrays`, you may wish to express that same data as PyTorch tensors, whether to take advantage of PyTorch’s GPU acceleration, or its efficient abstractions for building ML models. It’s easy to switch between `ndarrays` and PyTorch `tensors`:

In [30]:
import numpy as np
import torch

# Creating a NumPy array
numpy_array = np.ones((2, 3))
print("NumPy Array:")
print(numpy_array)

# Converting NumPy array to PyTorch tensor
pytorch_tensor = torch.from_numpy(numpy_array)
print("\nPyTorch Tensor:")
print(pytorch_tensor)

# Creating a random PyTorch tensor
pytorch_rand = torch.rand(2, 3)
print("\nRandom PyTorch Tensor:")
print(pytorch_rand)

# Converting PyTorch tensor to NumPy array
numpy_rand = pytorch_rand.numpy()
print("\nConverted NumPy Array:")
print(numpy_rand)

# Changes to NumPy array reflect in the PyTorch tensor and vice versa
numpy_array[1, 1] = 23
print("\nUpdated PyTorch Tensor from NumPy Array:")
print(pytorch_tensor)

pytorch_rand[1, 1] = 17
print("\nUpdated NumPy Array from PyTorch Tensor:")
print(numpy_rand)


NumPy Array:
[[1. 1. 1.]
 [1. 1. 1.]]

PyTorch Tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

Random PyTorch Tensor:
tensor([[0.7209, 0.7132, 0.7206],
        [0.9851, 0.0657, 0.6053]])

Converted NumPy Array:
[[0.7209366  0.71318144 0.7206389 ]
 [0.9850885  0.06566584 0.6053149 ]]

Updated PyTorch Tensor from NumPy Array:
tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64)

Updated NumPy Array from PyTorch Tensor:
[[ 0.7209366   0.71318144  0.7206389 ]
 [ 0.9850885  17.          0.6053149 ]]


It is important to know that these converted objects are using the ***same underlying memory*** as their
source objects, meaning that changes to one are reflected in the other:

In [31]:
numpy_array[1, 1] = 23
print(pytorch_tensor,"\n")
pytorch_rand[1, 1] = 17
print(numpy_rand)

tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64) 

[[ 0.7209366   0.71318144  0.7206389 ]
 [ 0.9850885  17.          0.6053149 ]]


### **Questions**

Given below are a few questions for you to solve. Do solve them as it will help reinforce the concepts we've learnt so far


1. Obtain a tensor containing only zeroes from the given tensor

In [32]:
pattern = torch.tensor([
    [1, 1, 1, 1],
    [1, 0, 0, 1],
    [1, 0, 0, 1],
    [1, 1, 1, 1]
])


zeros_tensor = torch.zeros_like(pattern)
print(zeros_tensor)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])


2. Create a Numpy array of shape (1,3,3) using PyTorch



In [33]:
np_from_torch = torch.rand(1, 3, 3).numpy()

print(np_from_torch)
print(type(np_from_torch))

[[[0.75132155 0.3739767  0.36231697]
  [0.23642415 0.91326284 0.66957337]
  [0.69045967 0.7940236  0.9694786 ]]]
<class 'numpy.ndarray'>


3. Create two random (2,2,2) tensors and find the max, min, mean, std of their product (matrix multiplication)

In [34]:
a = torch.rand(2, 2, 2)
b = torch.rand(2, 2, 2)

product = torch.matmul(a, b)

print(f"Product:\n{product}\n")
print(f"Max: {product.max()}")
print(f"Min: {product.min()}")
print(f"Mean: {product.mean()}")
print(f"Std: {product.std()}")

Product:
tensor([[[0.3844, 0.0726],
         [0.1175, 0.0205]],

        [[0.6323, 0.4652],
         [0.7356, 0.6276]]])

Max: 0.7356175184249878
Min: 0.020521700382232666
Mean: 0.38196489214897156
Std: 0.2806485593318939


4. Convert a 16x16 tensor into 1x256 tensor



In [35]:
big_tensor = torch.rand(16, 16)
flat_tensor = big_tensor.view(1, 256)

print(flat_tensor.shape)
print(flat_tensor)

torch.Size([1, 256])
tensor([[0.8770, 0.2143, 0.0390, 0.7638, 0.2215, 0.7781, 0.4066, 0.8798, 0.1287,
         0.1117, 0.2034, 0.7992, 0.2157, 0.1671, 0.9375, 0.2204, 0.7023, 0.4679,
         0.5031, 0.6971, 0.4695, 0.1693, 0.3993, 0.0919, 0.9075, 0.3568, 0.6219,
         0.9018, 0.8358, 0.9461, 0.5370, 0.8026, 0.5828, 0.9876, 0.1428, 0.2212,
         0.7728, 0.5082, 0.2206, 0.1655, 0.1846, 0.0190, 0.1032, 0.5021, 0.3315,
         0.1081, 0.2893, 0.6912, 0.8871, 0.5886, 0.0423, 0.6842, 0.5748, 0.0783,
         0.9065, 0.7688, 0.2456, 0.0158, 0.1465, 0.9523, 0.8653, 0.7184, 0.6956,
         0.3649, 0.7665, 0.3768, 0.2357, 0.0699, 0.7333, 0.2773, 0.8551, 0.5277,
         0.5169, 0.9717, 0.5319, 0.2077, 0.1986, 0.7198, 0.5014, 0.9169, 0.2262,
         0.8359, 0.9105, 0.1770, 0.2925, 0.2412, 0.8376, 0.7247, 0.0987, 0.4664,
         0.4907, 0.6620, 0.3100, 0.7774, 0.4758, 0.7765, 0.3657, 0.3645, 0.1769,
         0.3969, 0.7685, 0.0035, 0.9249, 0.1047, 0.0359, 0.7411, 0.1681, 0.2580,
       

5. Given two tensors x and Y, find the coefficients that best model the linear relationship `Y = ax + b` (Linear Regression)

In [36]:
# Generate sample data with a known linear relationship + noise
torch.manual_seed(0)
x = torch.linspace(0, 10, 100)
true_a, true_b = 2.5, 5.0
y = true_a * x + true_b + torch.randn(100,1)*2

# Initialize parameters that require gradients
a = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

lr = 0.01
epochs = 500

for epoch in range(epochs):
    y_pred = a * x + b
    loss = ((y_pred - y) ** 2).mean()

    loss.backward()

    with torch.no_grad():
        a -= lr * a.grad
        b -= lr * b.grad

    a.grad.zero_()
    b.grad.zero_()

    if epoch % 100 == 0:
        print(f"Epoch {epoch}: loss={loss.item():.4f}, a={a.item():.4f}, b={b.item():.4f}")

print(f"\nFinal coefficients: a={a.item():.4f}, b={b.item():.4f}")
print(f"True coefficients: a={true_a}, b={true_b}")

Epoch 0: loss=135.2432, a=2.6154, b=0.2555
Epoch 100: loss=6.3171, a=2.9323, b=2.1991
Epoch 200: loss=4.9812, a=2.7628, b=3.3263
Epoch 300: loss=4.4874, a=2.6598, b=4.0115
Epoch 400: loss=4.3049, a=2.5971, b=4.4282

Final coefficients: a=2.5594, b=4.6795
True coefficients: a=2.5, b=5.0


In this notebook, we covered the fundamental aspects of PyTorch and tensors, starting from installation to performing various operations.
By mastering these basics, you now have a solid foundation to build and train more complex machine learning models using PyTorch. Continue exploring PyTorch’s extensive library of functions and tools to further enhance your skills and tackle more advanced topics in deep learning and artificial intelligence.

Feel free to refer to the [PyTorch documentation](https://pytorch.org/docs/stable/index.html) for more detailed information and examples. Happy coding!